services:
  tentacle-plc:
    restart: always
    container_name: tentacle-plc
    image: joyja/kraken.tentacle:v0.0.1
    ports:
      - 4000:4000
    volumes:
      - tentacle-plc-development:/app/development:rw
    networks:
      - upstream
  tentacle-plc-front:
    restart: always
    container_name: tentacle-plc-ui
    image: joyja/kraken.tentacle-ui:v0.0.1
    ports:
      - 3000:3000
    networks:
      - upstream
    environment:
      - TENTACLE_HOST=tentacle-plc
  code-server:
    user: 0:0
    restart: always
    container_name: tentacle-plc-code-server
    image: codercom/code-server:4.22.0
    ports:
      - 8080:8080
    networks:
      - upstream
    volumes:
      - tentacle-plc-development:/home/coder/project:rw
    environment:
      - DOCKER_USER=root
      - PASSWORD=${CODE_SERVER_PASSWORD}
networks:
  upstream: {}
volumes:
  tentacle-plc-development: {}
