name: Squid Deploy Systemd

on:
  push:
    branches:
      - main # Set your deploying branch
    paths:
      - ".github/workflows/squid-deploy.yml"
      - "squid/back/**"
jobs:
  deploy:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [squid1, camophore]
    defaults:
      run:
        working-directory: ./squid/back
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify the Node.js version number, you can adjust as needed
          cache: "pnpm" # Caching pnpm modules

      - name: Set up pnpm
        uses: pnpm/actions-setup@v2.0.1
        with:
          version: 6.x # Specify the pnpm version to use; adjust as needed

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build

      - name: Prune to production dependencies
        run: pnpm prune --prod

      - name: Create user and group if they don't exist
        run: |
          #!/bin/bash
          set -eu

          # Check if the user exists and create it if not
          if ! id "squid-sa" &>/dev/null; then
            sudo adduser --disabled-password --gecos "" squid-sa
            # Be very cautious with the following line; it gives full sudo access
            echo "squid-sa ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/squid-sa
          fi

          # Check if the group exists and create it if not
          if ! getent group my_service_group; then
            sudo addgroup my_service_group
          fi

          # Check if the user is in the group and add it if not
          if ! id -nG "squid-sa" | grep -qw "my_service_group"; then
            sudo adduser squid-sa my_service_group
          fi

      - name: Set up the systemd service file
        run: |
          if [ ! -f /etc/systemd/system/squid.service ]; then
            echo '[Unit]
            Description=Squid Node.js App
            After=network.target

            [Service]
            Type=simple
            User=squid-sa
            Group=my_service_group
            WorkingDirectory=$GITHUB_WORKSPACE
            ExecStart=/usr/bin/node $GITHUB_WORKSPACE/build/src/index.js # Adjusted to your start script
            Restart=on-failure
            RestartSec=10
            StandardOutput=syslog
            StandardError=syslog
            SyslogIdentifier=squid

            [Install]
            WantedBy=multi-user.target' | sudo tee /etc/systemd/system/squid.service

            sudo systemctl daemon-reload
            sudo systemctl start squid
            sudo systemctl enable squid
          else
            # If the service file already exists, you might want to restart the service
            sudo systemctl restart squid
          fi
