on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'squid/back/src/**'
      - 'squid/back/scripts/**'
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./squid/back
    steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Run deploy script
      run: $GITHUB_WORKSPACE/squid/back/scripts/deploy.sh