on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'squid/back/src/**'
      - 'squid/back/scripts/**'
jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [squid1, camophore]
    defaults:
      run:
        working-directory: ./squid/back
    steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Run deploy script
      run: ./scripts/deploy.sh