name: Squid Deploy Systemd

on:
  push:
    branches:
      - main # Set your deploying branch
    paths:
      - ".github/workflows/squid-deploy.yml"
      - "squid/back/**"
jobs:
  deploy:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [squid1, camophore]
    defaults:
      run:
        working-directory: ./squid/back
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: pnpm install
      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm build

      - name: Prune to production dependencies
        run: pnpm prune --prod

      - name: Set up the systemd service file
        run: |
          if [ ! -f /etc/systemd/system/squid.service ]; then
            echo '[Unit]
            Description=Squid Node.js App
            After=network.target

            [Service]
            Type=simple
            User=joyja # Using the 'joyja' user here
            WorkingDirectory=$GITHUB_WORKSPACE
            ExecStart=/usr/bin/node $GITHUB_WORKSPACE/build/src/index.js # Adjusted to your start script
            Restart=on-failure
            RestartSec=10
            StandardOutput=syslog
            StandardError=syslog
            SyslogIdentifier=squid

            [Install]
            WantedBy=multi-user.target' | tee /etc/systemd/system/squid.service

            systemctl daemon-reload
            systemctl start squid
            systemctl enable squid
          else
            # If the service file already exists, you might want to restart the service
            systemctl restart squid
          fi
